[build.environment]
    NODE_VERSION = "18.12.1"
    NPM_VERSION = "8.19.2" 
    
[[plugins]]
  package = "@netlify/plugin-emails"

[build]
    functions= './functions'

[[redirects]]
    from = '/api/*'
    to = '/.netlify/functions/:splat'
    status= 200